### ISSUE TITLE
Fix Build Failure 

### ISSUE THREAD

**Issue by rexdivakar** [Open-Dev-Community/Tweet_data_hunter#11]
Currently the build fails due to missing of tweets.txt kindly run the program with ur credentials dump a small tweets file add it to the github repo for successful run.

![image](https://user-images.githubusercontent.com/15235122/94763150-1f186600-03c7-11eb-962c-2f1273cdea1d.png)

**Comment by AnaGVF** [comment]
Hello! 
I would like to solve this issue!

**Comment by rexdivakar** [comment]
Issue assigned to @AnaGVF 
🌟 Star it 🍴Fork it 🤝 Contribute to it!
Happy Coding..

Feel free to drop in https://discord.gg/59TDJgt

**Comment by AnaGVF** [comment]
I have finished and uploaded the tweets.txt file!
