### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by rexdivakar** [Open-Dev-Community/Tweet_data_hunter#13]
![image](https://user-images.githubusercontent.com/15235122/94877299-b937e700-0477-11eb-99f5-6f73f7472faa.png)

**Comment by refekt** [comment]
I'll give this a go

**Comment by rexdivakar** [comment]
Issue assigned to @refekt 
🌟 Star it 🍴Fork it 🤝 Contribute to it!
Happy Coding..

Feel free to drop in https://discord.gg/59TDJgt

**Comment by refekt** [comment]
I'm not getting this issue from my fork. 

```
C:\Users\aaa\AppData\Local\Programs\Python\Python37\python.exe C:/Users/aaa/Documents/GitHub/Tweet_data_hunter/text_analysis.py

Process finished with exit code 0
```

**Comment by rexdivakar** [comment]
U might have already installed nltk packages onto ur machine that's the reason @refekt

**Comment by refekt** [comment]
Not sure what to do then :(. I had to install the package after forking the code, but that's it.

**Comment by rexdivakar** [comment]
Try googling its a easier one, all u need to do is add a small change @refekt

**Comment by refekt** [comment]
Sorry! I will have to step back. I have to head to bed and I don't want to hold this Issue up. Thank you for the attempt!

**Comment by rexdivakar** [comment]
Oh k thanks, have a great day @refekt

**Comment by suparna13** [comment]
@rexdivakar Code run fine after installing requirements.txt using pip. Is anything else you are expecting on issue?

**Comment by suparna13** [comment]
@rexdivakar Can you please assign it to me I would like to contribute command to install dependencies from requirements.txt which would resolve the dependency issue you mentioned. Thank you.

**Comment by rexdivakar** [comment]
hey @suparna13  , hope u figured out the issue due to CI part assigning it to u let me know if u need any help

Issue assigned to @suparna13 
🌟 Star it 🍴Fork it 🤝 Contribute to it!
Happy Coding..

Feel free to drop in https://discord.gg/59TDJgt

**Comment by suparna13** [comment]
@rexdivakar I already raised PR https://github.com/Open-Dev-Community/Tweet_data_hunter/pull/18 which fixed this dependency issue. Can you please close this as PR is merged to master?
