### ISSUE TITLE
Adding Documentation

### ISSUE THREAD

**Issue by rexdivakar** [Open-Dev-Community/Tweet_data_hunter#2]
Go through the code and add documentation to them with clear README.md file

**Comment by Priyanshu-official** [comment]
I would like to Work on this @rexdivakar

**Comment by rexdivakar** [comment]
Issue assigned to @Priyanshu-official 
🌟 Star it 🍴Fork it 🤝 Contribute to it!
Happy Coding..

Feel free to drop in https://discord.gg/59TDJgt

**Comment by aastha-b** [comment]
I would live to work on this. Please explain what do I have to do

**Comment by rexdivakar** [comment]
Sorry buddy this issue is already assigned @aastha-b  please choose another issue. Thanks and happy coding 🙂

**Comment by Priyanshu-official** [comment]
@rexdivakar can you help me to explain a little bit about the Project
and What are the things I should add
